package molecule.sql.postgres.compliance.crud.update.attrOp

import molecule.coreTests.spi.crud.update.attrOp.decimal._
import molecule.sql.postgres.setup.Test_postgres_async


object Test_AttrOpSpecial_Float_ extends AttrOpDecimal_Float_ with Test_postgres_async
object Test_AttrOpSpecial_Double_ extends AttrOpDecimal_Double with Test_postgres_async
object Test_AttrOpSpecial_BigDecimal_ extends AttrOpDecimal_BigDecimal_ with Test_postgres_async

