package molecule.sql.postgres.compliance.aggregation

import molecule.coreTests.spi.aggregation.any._
import molecule.sql.postgres.setup.Test_postgres_async

object Test_AggrOne_String extends Aggr_String_ with Test_postgres_async
object Test_AggrOne_Int extends Aggr_Int with Test_postgres_async
object Test_AggrOne_Long extends Aggr_Long_ with Test_postgres_async
object Test_AggrOne_Float extends Aggr_Float_ with Test_postgres_async
object Test_AggrOne_Double extends Aggr_Double_ with Test_postgres_async
object Test_AggrOne_Boolean extends Aggr_Boolean with Test_postgres_async
object Test_AggrOne_BigInt extends Aggr_BigInt_ with Test_postgres_async
object Test_AggrOne_BigDecimal extends Aggr_BigDecimal_ with Test_postgres_async
object Test_AggrOne_Date extends Aggr_Date_ with Test_postgres_async
object Test_AggrOne_Duration extends Aggr_Duration_ with Test_postgres_async
object Test_AggrOne_Instant extends Aggr_Instant_ with Test_postgres_async
object Test_AggrOne_LocalDate extends Aggr_LocalDate_ with Test_postgres_async
object Test_AggrOne_LocalTime extends Aggr_LocalTime_ with Test_postgres_async
object Test_AggrOne_LocalDateTime extends Aggr_LocalDateTime_ with Test_postgres_async
object Test_AggrOne_OffsetTime extends Aggr_OffsetTime_ with Test_postgres_async
object Test_AggrOne_OffsetDateTime extends Aggr_OffsetDateTime_ with Test_postgres_async
object Test_AggrOne_ZonedDateTime extends Aggr_ZonedDateTime_ with Test_postgres_async
object Test_AggrOne_UUID extends Aggr_UUID_ with Test_postgres_async
object Test_AggrOne_URI extends Aggr_URI_ with Test_postgres_async
object Test_AggrOne_Byte extends Aggr_Byte_ with Test_postgres_async
object Test_AggrOne_Short extends Aggr_Short_ with Test_postgres_async
object Test_AggrOne_Char extends Aggr_Char_ with Test_postgres_async

object Test_AggrOne_ref extends Aggr_ref_ with Test_postgres_async
