package molecule.sql.postgres.compliance.aggr

import molecule.coreTests.spi.aggr.ref._
import molecule.sql.postgres.setup.Test_postgres_async

object Test_AggrOneRef_count extends AggrRef_count with Test_postgres_async
object Test_AggrOneRef_distinct extends AggrRef_distinct with Test_postgres_async
object Test_AggrOneRef_min_max extends AggrRef_min_max with Test_postgres_async
object Test_AggrOneRef_min_max_n extends AggrRef_min_max_n with Test_postgres_async
object Test_AggrOneRef_sample extends AggrRef_sample with Test_postgres_async
object Test_AggrOneRef_sample_n extends AggrRef_sample_n with Test_postgres_async
