package molecule.sql.postgres.compliance.aggr

import molecule.coreTests.spi.aggr.refNum._
import molecule.sql.postgres.setup.Test_postgres_async

object Test_AggrOneRefNum_sum extends AggrRefNum_sum with Test_postgres_async
object Test_AggrOneRefNum_median extends AggrRefNum_median with Test_postgres_async
object Test_AggrOneRefNum_avg extends AggrRefNum_avg with Test_postgres_async
object Test_AggrOneRefNum_variance extends AggrRefNum_variance with Test_postgres_async
object Test_AggrOneRefNum_stddev extends AggrRefNum_stddev with Test_postgres_async
