package molecule.core.marshalling

import java.io.FileNotFoundException
import java.net.URI
import java.util.Date
import boopickle.CompositePickler
import boopickle.Default._
import molecule.base.ast.SchemaAST._
import molecule.base.error._
import molecule.boilerplate.ast.Model._
import molecule.boilerplate.util.MoleculeLogging


object Boopicklers extends MoleculeLogging {

  implicit val pickleDate: Pickler[Date] = transformPickler((t: Long) => new java.util.Date(t))(_.getTime)
  implicit val pickleURI : Pickler[URI]  = transformPickler((t: String) => new URI(t))(_.toString)

  implicit val pickleCard: CompositePickler[Card] = compositePickler[Card]
  pickleCard.addConcreteType[CardOne.type]
  pickleCard.addConcreteType[CardSet.type]

  implicit val pickleMetaAttr  : CompositePickler[MetaAttr]   = compositePickler[MetaAttr]
  implicit val pickleMetaNs    : CompositePickler[MetaNs]     = compositePickler[MetaNs]
  implicit val pickleMetaPart  : CompositePickler[MetaPart]   = compositePickler[MetaPart]
  implicit val pickleMetaSchema: CompositePickler[MetaSchema] = compositePickler[MetaSchema]

  implicit val pickleMetaModel: CompositePickler[MetaModel] = compositePickler[MetaModel]
  pickleMetaModel.addConcreteType[MetaAttr]
  pickleMetaModel.addConcreteType[MetaNs]
  pickleMetaModel.addConcreteType[MetaPart]
  pickleMetaModel.addConcreteType[MetaSchema]

  implicit val pickleOp: CompositePickler[Op] = compositePickler[Op]
  pickleOp.addConcreteType[NoValue.type]
  pickleOp.addConcreteType[V.type]
  pickleOp.addConcreteType[Eq.type]
  pickleOp.addConcreteType[Neq.type]
  pickleOp.addConcreteType[Lt.type]
  pickleOp.addConcreteType[Le.type]
  pickleOp.addConcreteType[Gt.type]
  pickleOp.addConcreteType[Ge.type]
  pickleOp.addConcreteType[StartsWith.type]
  pickleOp.addConcreteType[EndsWith.type]
  pickleOp.addConcreteType[Contains.type]
  pickleOp.addConcreteType[Matches.type]
  pickleOp.addConcreteType[Take.type]
  pickleOp.addConcreteType[TakeRight.type]
  pickleOp.addConcreteType[Drop.type]
  pickleOp.addConcreteType[DropRight.type]
  pickleOp.addConcreteType[SubString.type]
  pickleOp.addConcreteType[Slice.type]
  pickleOp.addConcreteType[Remainder.type]
  pickleOp.addConcreteType[Even.type]
  pickleOp.addConcreteType[Odd.type]
  pickleOp.addConcreteType[Has.type]
  pickleOp.addConcreteType[HasNo.type]
  pickleOp.addConcreteType[Add.type]
  pickleOp.addConcreteType[Swap.type]
  pickleOp.addConcreteType[Remove.type]
  pickleOp.addConcreteType[Unify.type]
  pickleOp.addConcreteType[Fn]

  implicit val pickleValidator: CompositePickler[Validator] = compositePickler[Validator]
  pickleValidator.addConcreteType[ValidateString]
  pickleValidator.addConcreteType[ValidateInt]
  pickleValidator.addConcreteType[ValidateLong]
  pickleValidator.addConcreteType[ValidateFloat]
  pickleValidator.addConcreteType[ValidateDouble]
  pickleValidator.addConcreteType[ValidateBoolean]
  pickleValidator.addConcreteType[ValidateBigInt]
  pickleValidator.addConcreteType[ValidateBigDecimal]
  pickleValidator.addConcreteType[ValidateDate]
  pickleValidator.addConcreteType[ValidateUUID]
  pickleValidator.addConcreteType[ValidateURI]
  pickleValidator.addConcreteType[ValidateByte]
  pickleValidator.addConcreteType[ValidateShort]
  pickleValidator.addConcreteType[ValidateChar]

  implicit val pickleValue: CompositePickler[Value] = compositePickler[Value]
  pickleValue.addConcreteType[OneString]
  pickleValue.addConcreteType[OneInt]
  pickleValue.addConcreteType[OneLong]
  pickleValue.addConcreteType[OneFloat]
  pickleValue.addConcreteType[OneDouble]
  pickleValue.addConcreteType[OneBoolean]
  pickleValue.addConcreteType[OneBigInt]
  pickleValue.addConcreteType[OneBigDecimal]
  pickleValue.addConcreteType[OneDate]
  pickleValue.addConcreteType[OneUUID]
  pickleValue.addConcreteType[OneURI]
  pickleValue.addConcreteType[OneByte]
  pickleValue.addConcreteType[OneShort]
  pickleValue.addConcreteType[OneChar]

  implicit val pickleAttr: CompositePickler[Attr] = compositePickler[Attr]
  pickleAttr.addConcreteType[AttrOneManString]
  pickleAttr.addConcreteType[AttrOneManInt]
  pickleAttr.addConcreteType[AttrOneManLong]
  pickleAttr.addConcreteType[AttrOneManDouble]
  pickleAttr.addConcreteType[AttrOneManBoolean]
  pickleAttr.addConcreteType[AttrOneManBigInt]
  pickleAttr.addConcreteType[AttrOneManBigDecimal]
  pickleAttr.addConcreteType[AttrOneManDate]
  pickleAttr.addConcreteType[AttrOneManUUID]
  pickleAttr.addConcreteType[AttrOneManURI]
  pickleAttr.addConcreteType[AttrOneManByte]
  pickleAttr.addConcreteType[AttrOneManShort]
  pickleAttr.addConcreteType[AttrOneManFloat]
  pickleAttr.addConcreteType[AttrOneManChar]

  pickleAttr.addConcreteType[AttrOneOptString]
  pickleAttr.addConcreteType[AttrOneOptInt]
  pickleAttr.addConcreteType[AttrOneOptLong]
  pickleAttr.addConcreteType[AttrOneOptDouble]
  pickleAttr.addConcreteType[AttrOneOptBoolean]
  pickleAttr.addConcreteType[AttrOneOptBigInt]
  pickleAttr.addConcreteType[AttrOneOptBigDecimal]
  pickleAttr.addConcreteType[AttrOneOptDate]
  pickleAttr.addConcreteType[AttrOneOptUUID]
  pickleAttr.addConcreteType[AttrOneOptURI]
  pickleAttr.addConcreteType[AttrOneOptByte]
  pickleAttr.addConcreteType[AttrOneOptShort]
  pickleAttr.addConcreteType[AttrOneOptFloat]
  pickleAttr.addConcreteType[AttrOneOptChar]

  pickleAttr.addConcreteType[AttrOneTacString]
  pickleAttr.addConcreteType[AttrOneTacInt]
  pickleAttr.addConcreteType[AttrOneTacLong]
  pickleAttr.addConcreteType[AttrOneTacDouble]
  pickleAttr.addConcreteType[AttrOneTacBoolean]
  pickleAttr.addConcreteType[AttrOneTacBigInt]
  pickleAttr.addConcreteType[AttrOneTacBigDecimal]
  pickleAttr.addConcreteType[AttrOneTacDate]
  pickleAttr.addConcreteType[AttrOneTacUUID]
  pickleAttr.addConcreteType[AttrOneTacURI]
  pickleAttr.addConcreteType[AttrOneTacByte]
  pickleAttr.addConcreteType[AttrOneTacShort]
  pickleAttr.addConcreteType[AttrOneTacFloat]
  pickleAttr.addConcreteType[AttrOneTacChar]

  pickleAttr.addConcreteType[AttrSetManString]
  pickleAttr.addConcreteType[AttrSetManInt]
  pickleAttr.addConcreteType[AttrSetManLong]
  pickleAttr.addConcreteType[AttrSetManDouble]
  pickleAttr.addConcreteType[AttrSetManBoolean]
  pickleAttr.addConcreteType[AttrSetManBigInt]
  pickleAttr.addConcreteType[AttrSetManBigDecimal]
  pickleAttr.addConcreteType[AttrSetManDate]
  pickleAttr.addConcreteType[AttrSetManUUID]
  pickleAttr.addConcreteType[AttrSetManURI]
  pickleAttr.addConcreteType[AttrSetManByte]
  pickleAttr.addConcreteType[AttrSetManShort]
  pickleAttr.addConcreteType[AttrSetManFloat]
  pickleAttr.addConcreteType[AttrSetManChar]

  pickleAttr.addConcreteType[AttrSetOptString]
  pickleAttr.addConcreteType[AttrSetOptInt]
  pickleAttr.addConcreteType[AttrSetOptLong]
  pickleAttr.addConcreteType[AttrSetOptDouble]
  pickleAttr.addConcreteType[AttrSetOptBoolean]
  pickleAttr.addConcreteType[AttrSetOptBigInt]
  pickleAttr.addConcreteType[AttrSetOptBigDecimal]
  pickleAttr.addConcreteType[AttrSetOptDate]
  pickleAttr.addConcreteType[AttrSetOptUUID]
  pickleAttr.addConcreteType[AttrSetOptURI]
  pickleAttr.addConcreteType[AttrSetOptByte]
  pickleAttr.addConcreteType[AttrSetOptShort]
  pickleAttr.addConcreteType[AttrSetOptFloat]
  pickleAttr.addConcreteType[AttrSetOptChar]

  pickleAttr.addConcreteType[AttrSetTacString]
  pickleAttr.addConcreteType[AttrSetTacInt]
  pickleAttr.addConcreteType[AttrSetTacLong]
  pickleAttr.addConcreteType[AttrSetTacDouble]
  pickleAttr.addConcreteType[AttrSetTacBoolean]
  pickleAttr.addConcreteType[AttrSetTacBigInt]
  pickleAttr.addConcreteType[AttrSetTacBigDecimal]
  pickleAttr.addConcreteType[AttrSetTacDate]
  pickleAttr.addConcreteType[AttrSetTacUUID]
  pickleAttr.addConcreteType[AttrSetTacURI]
  pickleAttr.addConcreteType[AttrSetTacByte]
  pickleAttr.addConcreteType[AttrSetTacShort]
  pickleAttr.addConcreteType[AttrSetTacFloat]
  pickleAttr.addConcreteType[AttrSetTacChar]

  implicit val pickleElement: CompositePickler[Element] = compositePickler[Element]
  pickleElement.addConcreteType[Attr]
  pickleElement.addConcreteType[Ref]
  pickleElement.addConcreteType[BackRef]
  pickleElement.addConcreteType[Composite]
  pickleElement.addConcreteType[Nested]
  pickleElement.addConcreteType[NestedOpt]
  pickleElement.addConcreteType[TxMetaData]

  pickleElement.addConcreteType[AttrOneManString]
  pickleElement.addConcreteType[AttrOneManInt]
  pickleElement.addConcreteType[AttrOneManLong]
  pickleElement.addConcreteType[AttrOneManDouble]
  pickleElement.addConcreteType[AttrOneManBoolean]
  pickleElement.addConcreteType[AttrOneManBigInt]
  pickleElement.addConcreteType[AttrOneManBigDecimal]
  pickleElement.addConcreteType[AttrOneManDate]
  pickleElement.addConcreteType[AttrOneManUUID]
  pickleElement.addConcreteType[AttrOneManURI]
  pickleElement.addConcreteType[AttrOneManByte]
  pickleElement.addConcreteType[AttrOneManShort]
  pickleElement.addConcreteType[AttrOneManFloat]
  pickleElement.addConcreteType[AttrOneManChar]

  pickleElement.addConcreteType[AttrOneOptString]
  pickleElement.addConcreteType[AttrOneOptInt]
  pickleElement.addConcreteType[AttrOneOptLong]
  pickleElement.addConcreteType[AttrOneOptDouble]
  pickleElement.addConcreteType[AttrOneOptBoolean]
  pickleElement.addConcreteType[AttrOneOptBigInt]
  pickleElement.addConcreteType[AttrOneOptBigDecimal]
  pickleElement.addConcreteType[AttrOneOptDate]
  pickleElement.addConcreteType[AttrOneOptUUID]
  pickleElement.addConcreteType[AttrOneOptURI]
  pickleElement.addConcreteType[AttrOneOptByte]
  pickleElement.addConcreteType[AttrOneOptShort]
  pickleElement.addConcreteType[AttrOneOptFloat]
  pickleElement.addConcreteType[AttrOneOptChar]

  pickleElement.addConcreteType[AttrOneTacString]
  pickleElement.addConcreteType[AttrOneTacInt]
  pickleElement.addConcreteType[AttrOneTacLong]
  pickleElement.addConcreteType[AttrOneTacDouble]
  pickleElement.addConcreteType[AttrOneTacBoolean]
  pickleElement.addConcreteType[AttrOneTacBigInt]
  pickleElement.addConcreteType[AttrOneTacBigDecimal]
  pickleElement.addConcreteType[AttrOneTacDate]
  pickleElement.addConcreteType[AttrOneTacUUID]
  pickleElement.addConcreteType[AttrOneTacURI]
  pickleElement.addConcreteType[AttrOneTacByte]
  pickleElement.addConcreteType[AttrOneTacShort]
  pickleElement.addConcreteType[AttrOneTacFloat]
  pickleElement.addConcreteType[AttrOneTacChar]

  pickleElement.addConcreteType[AttrSetManString]
  pickleElement.addConcreteType[AttrSetManInt]
  pickleElement.addConcreteType[AttrSetManLong]
  pickleElement.addConcreteType[AttrSetManDouble]
  pickleElement.addConcreteType[AttrSetManBoolean]
  pickleElement.addConcreteType[AttrSetManBigInt]
  pickleElement.addConcreteType[AttrSetManBigDecimal]
  pickleElement.addConcreteType[AttrSetManDate]
  pickleElement.addConcreteType[AttrSetManUUID]
  pickleElement.addConcreteType[AttrSetManURI]
  pickleElement.addConcreteType[AttrSetManByte]
  pickleElement.addConcreteType[AttrSetManShort]
  pickleElement.addConcreteType[AttrSetManFloat]
  pickleElement.addConcreteType[AttrSetManChar]

  pickleElement.addConcreteType[AttrSetOptString]
  pickleElement.addConcreteType[AttrSetOptInt]
  pickleElement.addConcreteType[AttrSetOptLong]
  pickleElement.addConcreteType[AttrSetOptDouble]
  pickleElement.addConcreteType[AttrSetOptBoolean]
  pickleElement.addConcreteType[AttrSetOptBigInt]
  pickleElement.addConcreteType[AttrSetOptBigDecimal]
  pickleElement.addConcreteType[AttrSetOptDate]
  pickleElement.addConcreteType[AttrSetOptUUID]
  pickleElement.addConcreteType[AttrSetOptURI]
  pickleElement.addConcreteType[AttrSetOptByte]
  pickleElement.addConcreteType[AttrSetOptShort]
  pickleElement.addConcreteType[AttrSetOptFloat]
  pickleElement.addConcreteType[AttrSetOptChar]

  pickleElement.addConcreteType[AttrSetTacString]
  pickleElement.addConcreteType[AttrSetTacInt]
  pickleElement.addConcreteType[AttrSetTacLong]
  pickleElement.addConcreteType[AttrSetTacDouble]
  pickleElement.addConcreteType[AttrSetTacBoolean]
  pickleElement.addConcreteType[AttrSetTacBigInt]
  pickleElement.addConcreteType[AttrSetTacBigDecimal]
  pickleElement.addConcreteType[AttrSetTacDate]
  pickleElement.addConcreteType[AttrSetTacUUID]
  pickleElement.addConcreteType[AttrSetTacURI]
  pickleElement.addConcreteType[AttrSetTacByte]
  pickleElement.addConcreteType[AttrSetTacShort]
  pickleElement.addConcreteType[AttrSetTacFloat]
  pickleElement.addConcreteType[AttrSetTacChar]


  implicit val pickleInsertError: CompositePickler[InsertError] =
    compositePickler[InsertError]

  implicit val pickleExceptions: CompositePickler[Throwable] = exceptionPickler
  pickleExceptions
    .addConcreteType[MoleculeError]
    .addConcreteType[ModelError]
    .addConcreteType[ValidationErrors]
    .addConcreteType[InsertErrors]
    .addConcreteType[ExecutionError]

  implicit val pickleFileNotFoundEception: CompositePickler[FileNotFoundException] =
    compositePickler[FileNotFoundException]

  implicit val pickleConnProxy: CompositePickler[ConnProxy] =
    compositePickler[ConnProxy]
      .addConcreteType[DatomicProxy]
      .addConcreteType[JdbcProxy]
}
