package molecule.core.marshalling

import java.net.URI
import java.util.{Date, UUID}


case class DTO(
  rowCount: Int,
  levelCounts: List[List[Int]],
  oneString: List[String],
  oneInt: List[Int],
  oneLong: List[Long],
  oneFloat: List[Float],
  oneDouble: List[Double],
  oneBoolean: List[Boolean],
  oneBigInt: List[BigInt],
  oneBigDecimal: List[BigDecimal],
  oneDate: List[Date],
  oneUUID: List[UUID],
  oneURI: List[URI],
  oneByte: List[Byte],
  oneShort: List[Short],
  oneChar: List[Char],
  oneOptString: List[Option[String]],
  oneOptInt: List[Option[Int]],
  oneOptLong: List[Option[Long]],
  oneOptFloat: List[Option[Float]],
  oneOptDouble: List[Option[Double]],
  oneOptBoolean: List[Option[Boolean]],
  oneOptBigInt: List[Option[BigInt]],
  oneOptBigDecimal: List[Option[BigDecimal]],
  oneOptDate: List[Option[Date]],
  oneOptUUID: List[Option[UUID]],
  oneOptURI: List[Option[URI]],
  oneOptByte: List[Option[Byte]],
  oneOptShort: List[Option[Short]],
  oneOptChar: List[Option[Char]],
  setString: List[Set[String]],
  setInt: List[Set[Int]],
  setLong: List[Set[Long]],
  setFloat: List[Set[Float]],
  setDouble: List[Set[Double]],
  setBoolean: List[Set[Boolean]],
  setBigInt: List[Set[BigInt]],
  setBigDecimal: List[Set[BigDecimal]],
  setDate: List[Set[Date]],
  setUUID: List[Set[UUID]],
  setURI: List[Set[URI]],
  setByte: List[Set[Byte]],
  setShort: List[Set[Short]],
  setChar: List[Set[Char]],
  setOptString: List[Option[Set[String]]],
  setOptInt: List[Option[Set[Int]]],
  setOptLong: List[Option[Set[Long]]],
  setOptFloat: List[Option[Set[Float]]],
  setOptDouble: List[Option[Set[Double]]],
  setOptBoolean: List[Option[Set[Boolean]]],
  setOptBigInt: List[Option[Set[BigInt]]],
  setOptBigDecimal: List[Option[Set[BigDecimal]]],
  setOptDate: List[Option[Set[Date]]],
  setOptUUID: List[Option[Set[UUID]]],
  setOptURI: List[Option[Set[URI]]],
  setOptByte: List[Option[Set[Byte]]],
  setOptShort: List[Option[Set[Short]]],
  setOptChar: List[Option[Set[Char]]],
)
