package molecule.core.marshalling

import java.net.URI
import java.util.{Date, UUID}


case class DTO(
//  levelCounts: List[List[Int]],
//  counts: Array[Array[Array[Int]]] = Array(Array(Array.empty[Int])),
  rowCount: Int,
  oneString: Iterable[String],
  oneInt: Iterable[Int],
  oneLong: Iterable[Long],
  oneFloat: Iterable[Float],
  oneDouble: Iterable[Double],
  oneBoolean: Iterable[Boolean],
  oneBigInt: Iterable[BigInt],
  oneBigDecimal: Iterable[BigDecimal],
  oneDate: Iterable[Date],
  oneUUID: Iterable[UUID],
  oneURI: Iterable[URI],
  oneByte: Iterable[Byte],
  oneShort: Iterable[Short],
  oneChar: Iterable[Char],
  oneOptString: Iterable[Option[String]],
  oneOptInt: Iterable[Option[Int]],
  oneOptLong: Iterable[Option[Long]],
  oneOptFloat: Iterable[Option[Float]],
  oneOptDouble: Iterable[Option[Double]],
  oneOptBoolean: Iterable[Option[Boolean]],
  oneOptBigInt: Iterable[Option[BigInt]],
  oneOptBigDecimal: Iterable[Option[BigDecimal]],
  oneOptDate: Iterable[Option[Date]],
  oneOptUUID: Iterable[Option[UUID]],
  oneOptURI: Iterable[Option[URI]],
  oneOptByte: Iterable[Option[Byte]],
  oneOptShort: Iterable[Option[Short]],
  oneOptChar: Iterable[Option[Char]],
  setString: Iterable[Set[String]],
  setInt: Iterable[Set[Int]],
  setLong: Iterable[Set[Long]],
  setFloat: Iterable[Set[Float]],
  setDouble: Iterable[Set[Double]],
  setBoolean: Iterable[Set[Boolean]],
  setBigInt: Iterable[Set[BigInt]],
  setBigDecimal: Iterable[Set[BigDecimal]],
  setDate: Iterable[Set[Date]],
  setUUID: Iterable[Set[UUID]],
  setURI: Iterable[Set[URI]],
  setByte: Iterable[Set[Byte]],
  setShort: Iterable[Set[Short]],
  setChar: Iterable[Set[Char]],
  setOptString: Iterable[Option[Set[String]]],
  setOptInt: Iterable[Option[Set[Int]]],
  setOptLong: Iterable[Option[Set[Long]]],
  setOptFloat: Iterable[Option[Set[Float]]],
  setOptDouble: Iterable[Option[Set[Double]]],
  setOptBoolean: Iterable[Option[Set[Boolean]]],
  setOptBigInt: Iterable[Option[Set[BigInt]]],
  setOptBigDecimal: Iterable[Option[Set[BigDecimal]]],
  setOptDate: Iterable[Option[Set[Date]]],
  setOptUUID: Iterable[Option[Set[UUID]]],
  setOptURI: Iterable[Option[Set[URI]]],
  setOptByte: Iterable[Option[Set[Byte]]],
  setOptShort: Iterable[Option[Set[Short]]],
  setOptChar: Iterable[Option[Set[Char]]],
)
