package molecule.sql.mysql.compliance.pagination.cursor.noUnique

import molecule.coreTests.spi.pagination.cursor.noUnique._
import molecule.sql.mysql.setup.TestAsync_mysql

object Test_AttrOrderMandatory extends AttrOrderMandatory with TestAsync_mysql
object Test_AttrOrderOptional extends AttrOrderOptional with TestAsync_mysql
object Test_DirectionsMandatory extends DirectionsMandatory with TestAsync_mysql
object Test_DirectionsOptional extends DirectionsOptional with TestAsync_mysql
object Test_MutationAdd extends MutationAdd with TestAsync_mysql
object Test_MutationDelete extends MutationDelete with TestAsync_mysql
object Test_Nested extends Nested with TestAsync_mysql
object Test_OptNested extends OptNested with TestAsync_mysql
object Test_TypesOptional extends TypesOptional with TestAsync_mysql
