package molecule.document.mongodb.compliance2.pagination.cursor.noUnique

import molecule.coreTests.spi.pagination.cursor.noUnique._
import molecule.document.mongodb.setup.TestAsync_mongodb2

object AttrOrderMandatory extends AttrOrderMandatory with TestAsync_mongodb2
object AttrOrderOptional extends AttrOrderOptional with TestAsync_mongodb2
object DirectionsMandatory extends DirectionsMandatory with TestAsync_mongodb2
object DirectionsOptional extends DirectionsOptional with TestAsync_mongodb2
object MutationAdd extends MutationAdd with TestAsync_mongodb2
object MutationDelete extends MutationDelete with TestAsync_mongodb2
object Nested extends Nested with TestAsync_mongodb2
object NestedOpt extends NestedOpt with TestAsync_mongodb2
object TypesOptional extends TypesOptional with TestAsync_mongodb2
