// GENERATED CODE ********************************
package molecule.boilerplate.api

import molecule.boilerplate.api.expression._
import molecule.boilerplate.ops.ModelTransformations


trait ModelOps_0[t, Ns0[_], Ns1[_, _]]
  extends Molecule_00
    with ModelTransformations
    with ExprOneTacOps_0[t, Ns0]
    with ExprSetTacOps_0[t, Ns0]
    with Nested_0[Ns1]

trait ModelOps_1[A, t, Ns0[_, _], Ns1[_, _, _]]
  extends Molecule_01[A]
    with ModelTransformations
    with AggregatesOps_1[A, t, Ns0]
    with ExprOneManOps_1[A, t, Ns0]
    with ExprOneOptOps_1[A, t, Ns0]
    with ExprOneTacOps_1[A, t, Ns0]
    with ExprSetManOps_1[A, t, Ns0]
    with ExprSetOptOps_1[A, t, Ns0]
    with ExprSetTacOps_1[A, t, Ns0]
    with Nested_1[A, Ns1]
    with SortAttrsOps_1[A, t, Ns0]

trait ModelOps_2[A, B, t, Ns0[_, _, _], Ns1[_, _, _, _]]
  extends Molecule_02[A, B]
    with ModelTransformations
    with AggregatesOps_2[A, B, t, Ns0]
    with ExprOneManOps_2[A, B, t, Ns0]
    with ExprOneOptOps_2[A, B, t, Ns0]
    with ExprOneTacOps_2[A, B, t, Ns0]
    with ExprSetManOps_2[A, B, t, Ns0]
    with ExprSetOptOps_2[A, B, t, Ns0]
    with ExprSetTacOps_2[A, B, t, Ns0]
    with Nested_2[A, B, Ns1]
    with SortAttrsOps_2[A, B, t, Ns0]

trait ModelOps_3[A, B, C, t, Ns0[_, _, _, _], Ns1[_, _, _, _, _]]
  extends Molecule_03[A, B, C]
    with ModelTransformations
    with AggregatesOps_3[A, B, C, t, Ns0]
    with ExprOneManOps_3[A, B, C, t, Ns0]
    with ExprOneOptOps_3[A, B, C, t, Ns0]
    with ExprOneTacOps_3[A, B, C, t, Ns0]
    with ExprSetManOps_3[A, B, C, t, Ns0]
    with ExprSetOptOps_3[A, B, C, t, Ns0]
    with ExprSetTacOps_3[A, B, C, t, Ns0]
    with Nested_3[A, B, C, Ns1]
    with SortAttrsOps_3[A, B, C, t, Ns0]

trait ModelOps_4[A, B, C, D, t, Ns0[_, _, _, _, _], Ns1[_, _, _, _, _, _]]
  extends Molecule_04[A, B, C, D]
    with ModelTransformations
    with AggregatesOps_4[A, B, C, D, t, Ns0]
    with ExprOneManOps_4[A, B, C, D, t, Ns0]
    with ExprOneOptOps_4[A, B, C, D, t, Ns0]
    with ExprOneTacOps_4[A, B, C, D, t, Ns0]
    with ExprSetManOps_4[A, B, C, D, t, Ns0]
    with ExprSetOptOps_4[A, B, C, D, t, Ns0]
    with ExprSetTacOps_4[A, B, C, D, t, Ns0]
    with Nested_4[A, B, C, D, Ns1]
    with SortAttrsOps_4[A, B, C, D, t, Ns0]

trait ModelOps_5[A, B, C, D, E, t, Ns0[_, _, _, _, _, _], Ns1[_, _, _, _, _, _, _]]
  extends Molecule_05[A, B, C, D, E]
    with ModelTransformations
    with AggregatesOps_5[A, B, C, D, E, t, Ns0]
    with ExprOneManOps_5[A, B, C, D, E, t, Ns0]
    with ExprOneOptOps_5[A, B, C, D, E, t, Ns0]
    with ExprOneTacOps_5[A, B, C, D, E, t, Ns0]
    with ExprSetManOps_5[A, B, C, D, E, t, Ns0]
    with ExprSetOptOps_5[A, B, C, D, E, t, Ns0]
    with ExprSetTacOps_5[A, B, C, D, E, t, Ns0]
    with Nested_5[A, B, C, D, E, Ns1]
    with SortAttrsOps_5[A, B, C, D, E, t, Ns0]

trait ModelOps_6[A, B, C, D, E, F, t, Ns0[_, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _]]
  extends Molecule_06[A, B, C, D, E, F]
    with ModelTransformations
    with AggregatesOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprOneManOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprOneOptOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprOneTacOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprSetManOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprSetOptOps_6[A, B, C, D, E, F, t, Ns0]
    with ExprSetTacOps_6[A, B, C, D, E, F, t, Ns0]
    with Nested_6[A, B, C, D, E, F, Ns1]
    with SortAttrsOps_6[A, B, C, D, E, F, t, Ns0]

trait ModelOps_7[A, B, C, D, E, F, G, t, Ns0[_, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _]]
  extends Molecule_07[A, B, C, D, E, F, G]
    with ModelTransformations
    with AggregatesOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprOneManOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprOneOptOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprOneTacOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprSetManOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprSetOptOps_7[A, B, C, D, E, F, G, t, Ns0]
    with ExprSetTacOps_7[A, B, C, D, E, F, G, t, Ns0]
    with Nested_7[A, B, C, D, E, F, G, Ns1]
    with SortAttrsOps_7[A, B, C, D, E, F, G, t, Ns0]

trait ModelOps_8[A, B, C, D, E, F, G, H, t, Ns0[_, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _]]
  extends Molecule_08[A, B, C, D, E, F, G, H]
    with ModelTransformations
    with AggregatesOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprOneManOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprOneOptOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprOneTacOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprSetManOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprSetOptOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with ExprSetTacOps_8[A, B, C, D, E, F, G, H, t, Ns0]
    with Nested_8[A, B, C, D, E, F, G, H, Ns1]
    with SortAttrsOps_8[A, B, C, D, E, F, G, H, t, Ns0]

trait ModelOps_9[A, B, C, D, E, F, G, H, I, t, Ns0[_, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_09[A, B, C, D, E, F, G, H, I]
    with ModelTransformations
    with AggregatesOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprOneManOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprOneOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprOneTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprSetManOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprSetOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with ExprSetTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]
    with Nested_9[A, B, C, D, E, F, G, H, I, Ns1]
    with SortAttrsOps_9[A, B, C, D, E, F, G, H, I, t, Ns0]

trait ModelOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0[_, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_10[A, B, C, D, E, F, G, H, I, J]
    with ModelTransformations
    with AggregatesOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprOneManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprOneOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprOneTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprSetManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprSetOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with ExprSetTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]
    with Nested_10[A, B, C, D, E, F, G, H, I, J, Ns1]
    with SortAttrsOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns0]

trait ModelOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_11[A, B, C, D, E, F, G, H, I, J, K]
    with ModelTransformations
    with AggregatesOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprOneManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprOneOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprOneTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprSetManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprSetOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with ExprSetTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]
    with Nested_11[A, B, C, D, E, F, G, H, I, J, K, Ns1]
    with SortAttrsOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns0]

trait ModelOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_12[A, B, C, D, E, F, G, H, I, J, K, L]
    with ModelTransformations
    with AggregatesOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprOneManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprOneOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprOneTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprSetManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprSetOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with ExprSetTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]
    with Nested_12[A, B, C, D, E, F, G, H, I, J, K, L, Ns1]
    with SortAttrsOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns0]

trait ModelOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_13[A, B, C, D, E, F, G, H, I, J, K, L, M]
    with ModelTransformations
    with AggregatesOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprOneManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprOneOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprOneTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprSetManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprSetOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with ExprSetTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]
    with Nested_13[A, B, C, D, E, F, G, H, I, J, K, L, M, Ns1]
    with SortAttrsOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns0]

trait ModelOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
    with ModelTransformations
    with AggregatesOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprOneManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprOneOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprOneTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprSetManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprSetOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with ExprSetTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]
    with Nested_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, Ns1]
    with SortAttrsOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns0]

trait ModelOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
    with ModelTransformations
    with AggregatesOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprOneManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprOneOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprOneTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprSetManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprSetOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with ExprSetTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]
    with Nested_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Ns1]
    with SortAttrsOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns0]

trait ModelOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
    with ModelTransformations
    with AggregatesOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprOneManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprOneOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprOneTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprSetManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprSetOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with ExprSetTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]
    with Nested_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Ns1]
    with SortAttrsOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns0]

trait ModelOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
    with ModelTransformations
    with AggregatesOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprOneManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprOneOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprOneTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprSetManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprSetOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with ExprSetTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]
    with Nested_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Ns1]
    with SortAttrsOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns0]

trait ModelOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
    with ModelTransformations
    with AggregatesOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprOneManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprOneOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprOneTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprSetManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprSetOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with ExprSetTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]
    with Nested_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Ns1]
    with SortAttrsOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns0]

trait ModelOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
    with ModelTransformations
    with AggregatesOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprOneManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprOneOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprOneTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprSetManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprSetOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with ExprSetTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]
    with Nested_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Ns1]
    with SortAttrsOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns0]

trait ModelOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
    with ModelTransformations
    with AggregatesOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprOneManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprOneOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprOneTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprSetManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprSetOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with ExprSetTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]
    with Nested_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Ns1]
    with SortAttrsOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns0]

trait ModelOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
    with ModelTransformations
    with AggregatesOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprOneManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprOneOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprOneTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprSetManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprSetOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with ExprSetTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]
    with Nested_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Ns1]
    with SortAttrsOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns0]

trait ModelOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
    with ModelTransformations
    with AggregatesOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprOneManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprOneOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprOneTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprSetManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprSetOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with ExprSetTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]
    with SortAttrsOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns0]