package molecule.datalog.datomic.test.crud

import molecule.coreTests.test.crud.update.set.ops._
import molecule.datalog.datomic.setup.TestAsync_datomic

object UpdateSetOps_String_ extends UpdateSetOps_String_ with TestAsync_datomic
object UpdateSetOps_Int extends UpdateSetOps_Int with TestAsync_datomic
object UpdateSetOps_Long_ extends UpdateSetOps_Long_ with TestAsync_datomic
object UpdateSetOps_Float_ extends UpdateSetOps_Float_ with TestAsync_datomic
object UpdateSetOps_Double_ extends UpdateSetOps_Double_ with TestAsync_datomic
object UpdateSetOps_BigInt_ extends UpdateSetOps_BigInt_ with TestAsync_datomic
object UpdateSetOps_BigDecimal_ extends UpdateSetOps_BigDecimal_ with TestAsync_datomic
object UpdateSetOps_Date_ extends UpdateSetOps_Date_ with TestAsync_datomic
object UpdateSetOps_UUID_ extends UpdateSetOps_UUID_ with TestAsync_datomic
object UpdateSetOps_URI_ extends UpdateSetOps_URI_ with TestAsync_datomic
object UpdateSetOps_Byte_ extends UpdateSetOps_Byte_ with TestAsync_datomic
object UpdateSetOps_Short_ extends UpdateSetOps_Short_ with TestAsync_datomic
object UpdateSetOps_Char_ extends UpdateSetOps_Char_ with TestAsync_datomic

object UpdateSetOps_ref_ extends UpdateSetOps_ref_ with TestAsync_datomic
