package molecule.datalog.datomic.compliance.aggr.seq

import molecule.coreTests.spi.aggr.seq.refNum._
import molecule.datalog.datomic.setup.TestAsync_datomic

object AggrSeqRefNum_sum extends AggrSeqRefNum_sum with TestAsync_datomic
object AggrSeqRefNum_median extends AggrSeqRefNum_median with TestAsync_datomic
object AggrSeqRefNum_avg extends AggrSeqRefNum_avg with TestAsync_datomic
object AggrSeqRefNum_variance extends AggrSeqRefNum_variance with TestAsync_datomic
object AggrSeqRefNum_stddev extends AggrSeqRefNum_stddev with TestAsync_datomic
