package molecule.datalog.datomic.test.pagination.cursor.noUnique

import molecule.coreTests.test.pagination.cursor.noUnique._
import molecule.datalog.datomic.setup.TestAsync_datomic

object AttrOrderMandatory extends AttrOrderMandatory with TestAsync_datomic
object AttrOrderOptional extends AttrOrderOptional with TestAsync_datomic
object DirectionsMandatory extends DirectionsMandatory with TestAsync_datomic
object DirectionsOptional extends DirectionsOptional with TestAsync_datomic
object MutationAdd extends MutationAdd with TestAsync_datomic
object MutationDelete extends MutationDelete with TestAsync_datomic
object Nested extends Nested with TestAsync_datomic
object NestedOpt extends NestedOpt with TestAsync_datomic
object TypesOptional extends TypesOptional with TestAsync_datomic
