package molecule.datalog.datomic.compliance.pagination.cursor.noUnique

import molecule.coreTests.spi.pagination.cursor.noUnique._
import molecule.datalog.datomic.setup.Test_datomic_async

object Test_AttrOrderMandatory extends AttrOrderMandatory with Test_datomic_async
object Test_AttrOrderOptional extends AttrOrderOptional with Test_datomic_async
object Test_DirectionsMandatory extends DirectionsMandatory with Test_datomic_async
object Test_DirectionsOptional extends DirectionsOptional with Test_datomic_async
object Test_MutationAdd extends MutationAdd with Test_datomic_async
object Test_MutationDelete extends MutationDelete with Test_datomic_async
object Nested extends Nested with Test_datomic_async
object Test_OptNested extends OptNested with Test_datomic_async
object TypesOptional extends TypesOptional with Test_datomic_async
