package molecule.document.mongodb.compliance2.pagination.cursor.subUnique

import molecule.coreTests.spi.pagination.cursor.subUnique._
import molecule.document.mongodb.setup.TestAsync_mongodb2

object AttrOrder extends AttrOrder with TestAsync_mongodb2
object DirectionsStandardUnique extends DirectionsStandardUnique with TestAsync_mongodb2
object DirectionsUniqueStandard extends DirectionsUniqueStandard with TestAsync_mongodb2
object MutationAdd extends MutationAdd with TestAsync_mongodb2
object MutationDelete extends MutationDelete with TestAsync_mongodb2
object Nested extends Nested with TestAsync_mongodb2
object NestedOpt extends NestedOpt with TestAsync_mongodb2
object TypesUniqueValue extends TypesUniqueValue with TestAsync_mongodb2
