package molecule.sql.mariadb.test.aggr

import molecule.coreTests.test.aggr.set.number._
import molecule.sql.mariadb.setup.TestAsync_mariadb

object AggrSetNum_Int extends AggrSetNum_Int with TestAsync_mariadb
object AggrSetNum_Long extends AggrSetNum_Long_ with TestAsync_mariadb
object AggrSetNum_Float extends AggrSetNum_Float_ with TestAsync_mariadb
object AggrSetNum_Double extends AggrSetNum_Double_ with TestAsync_mariadb
object AggrSetNum_BigInt extends AggrSetNum_BigInt_ with TestAsync_mariadb
object AggrSetNum_BigDecimal extends AggrSetNum_BigDecimal_ with TestAsync_mariadb
object AggrSetNum_Byte extends AggrSetNum_Byte_ with TestAsync_mariadb
object AggrSetNum_Short extends AggrSetNum_Short_ with TestAsync_mariadb
object AggrSetNum_ref extends AggrSetNum_ref with TestAsync_mariadb
