package molecule.sql.postgres.compliance.pagination.cursor.noUnique

import molecule.coreTests.compliance.pagination.cursor.noUnique._
import molecule.sql.postgres.setup.TestAsync_postgres

object AttrOrderMandatory extends AttrOrderMandatory with TestAsync_postgres
object AttrOrderOptional extends AttrOrderOptional with TestAsync_postgres
object DirectionsMandatory extends DirectionsMandatory with TestAsync_postgres
object DirectionsOptional extends DirectionsOptional with TestAsync_postgres
object MutationAdd extends MutationAdd with TestAsync_postgres
object MutationDelete extends MutationDelete with TestAsync_postgres
object Nested extends Nested with TestAsync_postgres
object NestedOpt extends NestedOpt with TestAsync_postgres
object TypesOptional extends TypesOptional with TestAsync_postgres
