package molecule.sql.sqlite.compliance.filter.seq

import molecule.coreTests.spi.filter.seq.ref._
import molecule.coreTests.spi.filter.seq.types._
import molecule.sql.sqlite.setup.{TestAsync_sqlite, TestSuiteArray_sqlite}
import molecule.sql.sqlite.spi.SpiAsync_sqlite

object FilterSeq_String_ extends FilterSeq_String_ with TestAsync_sqlite
object FilterSeq_Int extends FilterSeq_Int with TestAsync_sqlite
object FilterSeq_Long_ extends FilterSeq_Long_ with TestAsync_sqlite
object FilterSeq_Float_ extends FilterSeq_Float_ with TestAsync_sqlite
object FilterSeq_Double_ extends FilterSeq_Double_ with TestAsync_sqlite
object FilterSeq_Boolean extends FilterSeq_Boolean with TestAsync_sqlite
object FilterSeq_BigInt_ extends FilterSeq_BigInt_ with TestAsync_sqlite
object FilterSeq_BigDecimal_ extends FilterSeq_BigDecimal_ with TestAsync_sqlite
object FilterSeq_Date_ extends FilterSeq_Date_ with TestAsync_sqlite
object FilterSeq_Duration_ extends FilterSeq_Duration_ with TestAsync_sqlite
object FilterSeq_Instant_ extends FilterSeq_Instant_ with TestAsync_sqlite
object FilterSeq_LocalDate_ extends FilterSeq_LocalDate_ with TestAsync_sqlite
object FilterSeq_LocalTime_ extends FilterSeq_LocalTime_ with TestAsync_sqlite
object FilterSeq_LocalDateTime_ extends FilterSeq_LocalDateTime_ with TestAsync_sqlite
object FilterSeq_OffsetTime_ extends FilterSeq_OffsetTime_ with TestAsync_sqlite
object FilterSeq_OffsetDateTime_ extends FilterSeq_OffsetDateTime_ with TestAsync_sqlite
object FilterSeq_ZonedDateTime_ extends FilterSeq_ZonedDateTime_ with TestAsync_sqlite
object FilterSeq_UUID_ extends FilterSeq_UUID_ with TestAsync_sqlite
object FilterSeq_URI_ extends FilterSeq_URI_ with TestAsync_sqlite
object FilterSeq_ByteArray extends FilterSeq_ByteArray with TestSuiteArray_sqlite with SpiAsync_sqlite
object FilterSeq_Short_ extends FilterSeq_Short_ with TestAsync_sqlite
object FilterSeq_Char_ extends FilterSeq_Char_ with TestAsync_sqlite


object FilterRefSeq_Card1Ref extends FilterRefSeq_Card1Ref with TestAsync_sqlite
object FilterRefSeq_Card1RefOwned extends FilterRefSeq_Card1RefOwned with TestAsync_sqlite
object FilterRefSeq_Card2Ref extends FilterRefSeq_Card2Ref with TestAsync_sqlite
object FilterRefSeq_Card2RefOwned extends FilterRefSeq_Card2RefOwned with TestAsync_sqlite
