package molecule.datalog.datomic.compliance.validation

import molecule.coreTests.compliance.validation.KeywordSubstitution
import molecule.datalog.datomic.setup.TestAsync_datomic

object KeywordSubstitution extends KeywordSubstitution with TestAsync_datomic
