package molecule.datalog.datomic.compliance.validation

import molecule.coreTests.spi.validation.KeywordSubstitution
import molecule.datalog.datomic.setup.Test_datomic_async

object Test_KeywordSubstitution extends KeywordSubstitution with Test_datomic_async
