package molecule.datalog.datomic.compliance.validation

import molecule.coreTests.spi.validation.StringValidationFns
import molecule.datalog.datomic.setup.Test_datomic_async

object Test_StringValidationFns extends StringValidationFns with Test_datomic_async
