package molecule.datalog.datomic.compliance.aggr.set

import molecule.coreTests.spi.aggr.set.refNum._
import molecule.datalog.datomic.setup.TestAsync_datomic

object AggrSetRefNum_sum extends AggrSetRefNum_sum with TestAsync_datomic
object AggrSetRefNum_median extends AggrSetRefNum_median with TestAsync_datomic
object AggrSetRefNum_avg extends AggrSetRefNum_avg with TestAsync_datomic
object AggrSetRefNum_variance extends AggrSetRefNum_variance with TestAsync_datomic
object AggrSetRefNum_stddev extends AggrSetRefNum_stddev with TestAsync_datomic
