package molecule.datalog.datomic.compliance.aggr.set

import molecule.coreTests.spi.aggr.set.any._
import molecule.datalog.datomic.setup.TestAsync_datomic

object AggrSet_String_ extends AggrSet_String_ with TestAsync_datomic
object AggrSet_Int extends AggrSet_Int with TestAsync_datomic
object AggrSet_Long_ extends AggrSet_Long_ with TestAsync_datomic
object AggrSet_Float_ extends AggrSet_Float_ with TestAsync_datomic
object AggrSet_Double_ extends AggrSet_Double_ with TestAsync_datomic
object AggrSet_Boolean extends AggrSet_Boolean with TestAsync_datomic
object AggrSet_BigInt_ extends AggrSet_BigInt_ with TestAsync_datomic
object AggrSet_BigDecimal_ extends AggrSet_BigDecimal_ with TestAsync_datomic
object AggrSet_Date_ extends AggrSet_Date_ with TestAsync_datomic
object AggrSet_Duration_ extends AggrSet_Duration_ with TestAsync_datomic
object AggrSet_Instant_ extends AggrSet_Instant_ with TestAsync_datomic
object AggrSet_LocalDate_ extends AggrSet_LocalDate_ with TestAsync_datomic
object AggrSet_LocalTime_ extends AggrSet_LocalTime_ with TestAsync_datomic
object AggrSet_LocalDateTime_ extends AggrSet_LocalDateTime_ with TestAsync_datomic
object AggrSet_OffsetTime_ extends AggrSet_OffsetTime_ with TestAsync_datomic
object AggrSet_OffsetDateTime_ extends AggrSet_OffsetDateTime_ with TestAsync_datomic
object AggrSet_ZonedDateTime_ extends AggrSet_ZonedDateTime_ with TestAsync_datomic
object AggrSet_UUID_ extends AggrSet_UUID_ with TestAsync_datomic
object AggrSet_URI_ extends AggrSet_URI_ with TestAsync_datomic
object AggrSet_Byte_ extends AggrSet_Byte_ with TestAsync_datomic
object AggrSet_Short_ extends AggrSet_Short_ with TestAsync_datomic
object AggrSet_Char_ extends AggrSet_Char_ with TestAsync_datomic

object AggrSet_ref extends AggrSet_ref with TestAsync_datomic
