package molecule.document.mongodb.compliance2.aggr

import molecule.coreTests.spi.aggr.set.number._
import molecule.document.mongodb.setup.TestAsync_mongodb2

object AggrSetNum_Int extends AggrSetNum_Int with TestAsync_mongodb2
object AggrSetNum_Long extends AggrSetNum_Long_ with TestAsync_mongodb2
object AggrSetNum_Float extends AggrSetNum_Float_ with TestAsync_mongodb2
object AggrSetNum_Double extends AggrSetNum_Double_ with TestAsync_mongodb2
object AggrSetNum_BigInt extends AggrSetNum_BigInt_ with TestAsync_mongodb2
object AggrSetNum_BigDecimal extends AggrSetNum_BigDecimal_ with TestAsync_mongodb2
object AggrSetNum_Byte extends AggrSetNum_Byte_ with TestAsync_mongodb2
object AggrSetNum_Short extends AggrSetNum_Short_ with TestAsync_mongodb2
