package molecule.document.mongodb.compliance2.aggr

import molecule.coreTests.spi.aggr.set.refNum._
import molecule.document.mongodb.setup.TestAsync_mongodb2

object AggrSetRefNum_sum extends AggrSetRefNum_sum with TestAsync_mongodb2
object AggrSetRefNum_median extends AggrSetRefNum_median with TestAsync_mongodb2
object AggrSetRefNum_avg extends AggrSetRefNum_avg with TestAsync_mongodb2
object AggrSetRefNum_variance extends AggrSetRefNum_variance with TestAsync_mongodb2
object AggrSetRefNum_stddev extends AggrSetRefNum_stddev with TestAsync_mongodb2
