package molecule.document.mongodb.compliance2.aggr

import molecule.coreTests.spi.aggr.one.refNum._
import molecule.document.mongodb.setup.TestAsync_mongodb2

object AggrOneRefNum_sum extends AggrOneRefNum_sum with TestAsync_mongodb2
object AggrOneRefNum_median extends AggrOneRefNum_median with TestAsync_mongodb2
object AggrOneRefNum_avg extends AggrOneRefNum_avg with TestAsync_mongodb2
object AggrOneRefNum_variance extends AggrOneRefNum_variance with TestAsync_mongodb2
object AggrOneRefNum_stddev extends AggrOneRefNum_stddev with TestAsync_mongodb2
