// GENERATED CODE ********************************
package molecule.boilerplate.api

import molecule.boilerplate.api.expression._
import molecule.boilerplate.ops.ModelTransformations_


trait ModelOps_0[t, Ns1[_], Ns2[_, _]]
  extends Molecule_00
    with ModelTransformations_
    with ExprOneTacOps_0[t, Ns1, Ns2]
    with ExprSetTacOps_0[t, Ns1, Ns2]
    with ExprArrTacOps_0[t, Ns1, Ns2]
    with ExprMapTacOps_0[t, Ns1, Ns2]

trait ModelOps_1[A, t, Ns1[_, _], Ns2[_, _, _]]
  extends Molecule_01[A]
    with ModelTransformations_
    with AggregatesOps_1[A, t, Ns1]
    with ExprOneManOps_1[A, t, Ns1, Ns2]
    with ExprOneOptOps_1[A, t, Ns1, Ns2]
    with ExprOneTacOps_1[A, t, Ns1, Ns2]
    with ExprSetManOps_1[A, t, Ns1, Ns2]
    with ExprSetOptOps_1[A, t, Ns1, Ns2]
    with ExprSetTacOps_1[A, t, Ns1, Ns2]
    with ExprArrManOps_1[A, t, Ns1, Ns2]
    with ExprArrOptOps_1[A, t, Ns1, Ns2]
    with ExprArrTacOps_1[A, t, Ns1, Ns2]
    with ExprMapManOps_1[A, t, Ns1, Ns2]
    with ExprMapOptOps_1[A, t, Ns1, Ns2]
    with ExprMapTacOps_1[A, t, Ns1, Ns2]
    with SortAttrsOps_1[A, t, Ns1]

trait ModelOps_2[A, B, t, Ns1[_, _, _], Ns2[_, _, _, _]]
  extends Molecule_02[A, B]
    with ModelTransformations_
    with AggregatesOps_2[A, B, t, Ns1]
    with ExprOneManOps_2[A, B, t, Ns1, Ns2]
    with ExprOneOptOps_2[A, B, t, Ns1, Ns2]
    with ExprOneTacOps_2[A, B, t, Ns1, Ns2]
    with ExprSetManOps_2[A, B, t, Ns1, Ns2]
    with ExprSetOptOps_2[A, B, t, Ns1, Ns2]
    with ExprSetTacOps_2[A, B, t, Ns1, Ns2]
    with ExprArrManOps_2[A, B, t, Ns1, Ns2]
    with ExprArrOptOps_2[A, B, t, Ns1, Ns2]
    with ExprArrTacOps_2[A, B, t, Ns1, Ns2]
    with ExprMapManOps_2[A, B, t, Ns1, Ns2]
    with ExprMapOptOps_2[A, B, t, Ns1, Ns2]
    with ExprMapTacOps_2[A, B, t, Ns1, Ns2]
    with SortAttrsOps_2[A, B, t, Ns1]

trait ModelOps_3[A, B, C, t, Ns1[_, _, _, _], Ns2[_, _, _, _, _]]
  extends Molecule_03[A, B, C]
    with ModelTransformations_
    with AggregatesOps_3[A, B, C, t, Ns1]
    with ExprOneManOps_3[A, B, C, t, Ns1, Ns2]
    with ExprOneOptOps_3[A, B, C, t, Ns1, Ns2]
    with ExprOneTacOps_3[A, B, C, t, Ns1, Ns2]
    with ExprSetManOps_3[A, B, C, t, Ns1, Ns2]
    with ExprSetOptOps_3[A, B, C, t, Ns1, Ns2]
    with ExprSetTacOps_3[A, B, C, t, Ns1, Ns2]
    with ExprArrManOps_3[A, B, C, t, Ns1, Ns2]
    with ExprArrOptOps_3[A, B, C, t, Ns1, Ns2]
    with ExprArrTacOps_3[A, B, C, t, Ns1, Ns2]
    with ExprMapManOps_3[A, B, C, t, Ns1, Ns2]
    with ExprMapOptOps_3[A, B, C, t, Ns1, Ns2]
    with ExprMapTacOps_3[A, B, C, t, Ns1, Ns2]
    with SortAttrsOps_3[A, B, C, t, Ns1]

trait ModelOps_4[A, B, C, D, t, Ns1[_, _, _, _, _], Ns2[_, _, _, _, _, _]]
  extends Molecule_04[A, B, C, D]
    with ModelTransformations_
    with AggregatesOps_4[A, B, C, D, t, Ns1]
    with ExprOneManOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprOneOptOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprOneTacOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprSetManOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprSetOptOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprSetTacOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprArrManOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprArrOptOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprArrTacOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprMapManOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprMapOptOps_4[A, B, C, D, t, Ns1, Ns2]
    with ExprMapTacOps_4[A, B, C, D, t, Ns1, Ns2]
    with SortAttrsOps_4[A, B, C, D, t, Ns1]

trait ModelOps_5[A, B, C, D, E, t, Ns1[_, _, _, _, _, _], Ns2[_, _, _, _, _, _, _]]
  extends Molecule_05[A, B, C, D, E]
    with ModelTransformations_
    with AggregatesOps_5[A, B, C, D, E, t, Ns1]
    with ExprOneManOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprOneOptOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprOneTacOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprSetManOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprSetOptOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprSetTacOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprArrManOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprArrOptOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprArrTacOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprMapManOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprMapOptOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with ExprMapTacOps_5[A, B, C, D, E, t, Ns1, Ns2]
    with SortAttrsOps_5[A, B, C, D, E, t, Ns1]

trait ModelOps_6[A, B, C, D, E, F, t, Ns1[_, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _]]
  extends Molecule_06[A, B, C, D, E, F]
    with ModelTransformations_
    with AggregatesOps_6[A, B, C, D, E, F, t, Ns1]
    with ExprOneManOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprOneOptOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprOneTacOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprSetManOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprSetOptOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprSetTacOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprArrManOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprArrOptOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprArrTacOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprMapManOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprMapOptOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with ExprMapTacOps_6[A, B, C, D, E, F, t, Ns1, Ns2]
    with SortAttrsOps_6[A, B, C, D, E, F, t, Ns1]

trait ModelOps_7[A, B, C, D, E, F, G, t, Ns1[_, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _]]
  extends Molecule_07[A, B, C, D, E, F, G]
    with ModelTransformations_
    with AggregatesOps_7[A, B, C, D, E, F, G, t, Ns1]
    with ExprOneManOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprOneOptOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprOneTacOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprSetManOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprSetOptOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprSetTacOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprArrManOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprArrOptOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprArrTacOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprMapManOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprMapOptOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with ExprMapTacOps_7[A, B, C, D, E, F, G, t, Ns1, Ns2]
    with SortAttrsOps_7[A, B, C, D, E, F, G, t, Ns1]

trait ModelOps_8[A, B, C, D, E, F, G, H, t, Ns1[_, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _]]
  extends Molecule_08[A, B, C, D, E, F, G, H]
    with ModelTransformations_
    with AggregatesOps_8[A, B, C, D, E, F, G, H, t, Ns1]
    with ExprOneManOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprOneOptOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprOneTacOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprSetManOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprSetOptOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprSetTacOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprArrManOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprArrOptOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprArrTacOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprMapManOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprMapOptOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with ExprMapTacOps_8[A, B, C, D, E, F, G, H, t, Ns1, Ns2]
    with SortAttrsOps_8[A, B, C, D, E, F, G, H, t, Ns1]

trait ModelOps_9[A, B, C, D, E, F, G, H, I, t, Ns1[_, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_09[A, B, C, D, E, F, G, H, I]
    with ModelTransformations_
    with AggregatesOps_9[A, B, C, D, E, F, G, H, I, t, Ns1]
    with ExprOneManOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprOneOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprOneTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprSetManOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprSetOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprSetTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprArrManOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprArrOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprArrTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprMapManOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprMapOptOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with ExprMapTacOps_9[A, B, C, D, E, F, G, H, I, t, Ns1, Ns2]
    with SortAttrsOps_9[A, B, C, D, E, F, G, H, I, t, Ns1]

trait ModelOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1[_, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_10[A, B, C, D, E, F, G, H, I, J]
    with ModelTransformations_
    with AggregatesOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1]
    with ExprOneManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprOneOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprOneTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprSetManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprSetOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprSetTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprArrManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprArrOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprArrTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprMapManOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprMapOptOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with ExprMapTacOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1, Ns2]
    with SortAttrsOps_10[A, B, C, D, E, F, G, H, I, J, t, Ns1]

trait ModelOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_11[A, B, C, D, E, F, G, H, I, J, K]
    with ModelTransformations_
    with AggregatesOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1]
    with ExprOneManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprOneOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprOneTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprSetManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprSetOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprSetTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprArrManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprArrOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprArrTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprMapManOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprMapOptOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with ExprMapTacOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1, Ns2]
    with SortAttrsOps_11[A, B, C, D, E, F, G, H, I, J, K, t, Ns1]

trait ModelOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_12[A, B, C, D, E, F, G, H, I, J, K, L]
    with ModelTransformations_
    with AggregatesOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1]
    with ExprOneManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprOneOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprOneTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprSetManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprSetOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprSetTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprArrManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprArrOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprArrTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprMapManOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprMapOptOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with ExprMapTacOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1, Ns2]
    with SortAttrsOps_12[A, B, C, D, E, F, G, H, I, J, K, L, t, Ns1]

trait ModelOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_13[A, B, C, D, E, F, G, H, I, J, K, L, M]
    with ModelTransformations_
    with AggregatesOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1]
    with ExprOneManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprOneOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprOneTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprSetManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprSetOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprSetTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprArrManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprArrOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprArrTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprMapManOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprMapOptOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with ExprMapTacOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1, Ns2]
    with SortAttrsOps_13[A, B, C, D, E, F, G, H, I, J, K, L, M, t, Ns1]

trait ModelOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
    with ModelTransformations_
    with AggregatesOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1]
    with ExprOneManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprOneOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprOneTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprSetManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprSetOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprSetTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprArrManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprArrOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprArrTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprMapManOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprMapOptOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with ExprMapTacOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1, Ns2]
    with SortAttrsOps_14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, t, Ns1]

trait ModelOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
    with ModelTransformations_
    with AggregatesOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1]
    with ExprOneManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprOneOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprOneTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprSetManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprSetOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprSetTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprArrManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprArrOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprArrTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprMapManOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprMapOptOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with ExprMapTacOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1, Ns2]
    with SortAttrsOps_15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, t, Ns1]

trait ModelOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
    with ModelTransformations_
    with AggregatesOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1]
    with ExprOneManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprOneOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprOneTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprSetManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprSetOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprSetTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprArrManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprArrOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprArrTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprMapManOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprMapOptOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with ExprMapTacOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1, Ns2]
    with SortAttrsOps_16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, t, Ns1]

trait ModelOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
    with ModelTransformations_
    with AggregatesOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1]
    with ExprOneManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprOneOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprOneTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprSetManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprSetOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprSetTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprArrManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprArrOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprArrTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprMapManOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprMapOptOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with ExprMapTacOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1, Ns2]
    with SortAttrsOps_17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, t, Ns1]

trait ModelOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
    with ModelTransformations_
    with AggregatesOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1]
    with ExprOneManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprOneOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprOneTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprSetManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprSetOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprSetTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprArrManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprArrOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprArrTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprMapManOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprMapOptOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with ExprMapTacOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1, Ns2]
    with SortAttrsOps_18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, t, Ns1]

trait ModelOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
    with ModelTransformations_
    with AggregatesOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1]
    with ExprOneManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprOneOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprOneTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprSetManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprSetOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprSetTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprArrManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprArrOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprArrTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprMapManOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprMapOptOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with ExprMapTacOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1, Ns2]
    with SortAttrsOps_19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, t, Ns1]

trait ModelOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
    with ModelTransformations_
    with AggregatesOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1]
    with ExprOneManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprOneOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprOneTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprSetManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprSetOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprSetTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprArrManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprArrOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprArrTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprMapManOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprMapOptOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with ExprMapTacOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1, Ns2]
    with SortAttrsOps_20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, t, Ns1]

trait ModelOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
    with ModelTransformations_
    with AggregatesOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1]
    with ExprOneManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprOneOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprOneTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprSetManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprSetOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprSetTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprArrManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprArrOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprArrTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprMapManOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprMapOptOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with ExprMapTacOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1, Ns2]
    with SortAttrsOps_21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, t, Ns1]

trait ModelOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _], Ns2[_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _]]
  extends Molecule_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
    with ModelTransformations_
    with AggregatesOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1]
    with ExprOneManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprOneOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprOneTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprSetManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprSetOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprSetTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprArrManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprArrOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprArrTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprMapManOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprMapOptOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with ExprMapTacOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1, Ns2]
    with SortAttrsOps_22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, t, Ns1]