package molecule.datalog.datomic.compliance.relation

import molecule.coreTests.spi.relation.nested._
import molecule.datalog.datomic.setup.{Test_datomic_async, TestSuite_datomic_array}
import molecule.datalog.datomic.spi.Spi_datomic_async

object Test_NestedBasic extends NestedBasic with Test_datomic_async
object Test_NestedExpr extends NestedExpr with Test_datomic_async
object Test_NestedLevels extends NestedLevels with Test_datomic_async
object Test_NestedOptional extends NestedOptional with Test_datomic_async
object Test_NestedRef extends NestedRef with Test_datomic_async
object Test_NestedSemantics extends NestedSemantics with Test_datomic_async
object Test_NestedTypes extends NestedTypes with TestSuite_datomic_array with Spi_datomic_async
