package molecule.datalog.datomic.compliance.crud

import molecule.coreTests.spi.crud.update.array.ops._
import molecule.datalog.datomic.setup.TestAsync_datomic

object UpdateArrayOps_String_ extends UpdateArrayOps_String_ with TestAsync_datomic
object UpdateArrayOps_Int extends UpdateArrayOps_Int with TestAsync_datomic
object UpdateArrayOps_Long_ extends UpdateArrayOps_Long_ with TestAsync_datomic
object UpdateArrayOps_Float_ extends UpdateArrayOps_Float_ with TestAsync_datomic
object UpdateArrayOps_Double_ extends UpdateArrayOps_Double_ with TestAsync_datomic
object UpdateArrayOps_BigInt_ extends UpdateArrayOps_BigInt_ with TestAsync_datomic
object UpdateArrayOps_BigDecimal_ extends UpdateArrayOps_BigDecimal_ with TestAsync_datomic
object UpdateArrayOps_Date_ extends UpdateArrayOps_Date_ with TestAsync_datomic
object UpdateArrayOps_Duration_ extends UpdateArrayOps_Duration_ with TestAsync_datomic
object UpdateArrayOps_Instant_ extends UpdateArrayOps_Instant_ with TestAsync_datomic
object UpdateArrayOps_LocalDate_ extends UpdateArrayOps_LocalDate_ with TestAsync_datomic
object UpdateArrayOps_LocalTime_ extends UpdateArrayOps_LocalTime_ with TestAsync_datomic
object UpdateArrayOps_LocalDateTime_ extends UpdateArrayOps_LocalDateTime_ with TestAsync_datomic
object UpdateArrayOps_OffsetTime_ extends UpdateArrayOps_OffsetTime_ with TestAsync_datomic
object UpdateArrayOps_OffsetDateTime_ extends UpdateArrayOps_OffsetDateTime_ with TestAsync_datomic
object UpdateArrayOps_ZonedDateTime_ extends UpdateArrayOps_ZonedDateTime_ with TestAsync_datomic
object UpdateArrayOps_UUID_ extends UpdateArrayOps_UUID_ with TestAsync_datomic
object UpdateArrayOps_URI_ extends UpdateArrayOps_URI_ with TestAsync_datomic
object UpdateArrayOps_Byte_ extends UpdateArrayOps_Byte with TestAsync_datomic
object UpdateArrayOps_Short_ extends UpdateArrayOps_Short_ with TestAsync_datomic
object UpdateArrayOps_Char_ extends UpdateArrayOps_Char_ with TestAsync_datomic
