package molecule.sql.mariadb.compliance.pagination.cursor.noUnique

import molecule.coreTests.spi.pagination.cursor.noUnique._
import molecule.sql.mariadb.setup.TestAsync_mariadb

object Test_AttrOrderMandatory extends AttrOrderMandatory with TestAsync_mariadb
object Test_AttrOrderOptional extends AttrOrderOptional with TestAsync_mariadb
object Test_DirectionsMandatory extends DirectionsMandatory with TestAsync_mariadb
object Test_DirectionsOptional extends DirectionsOptional with TestAsync_mariadb
object Test_MutationAdd extends MutationAdd with TestAsync_mariadb
object Test_MutationDelete extends MutationDelete with TestAsync_mariadb
object Test_Nested extends Nested with TestAsync_mariadb
object Test_OptNested extends OptNested with TestAsync_mariadb
object Test_TypesOptional extends TypesOptional with TestAsync_mariadb
