package molecule.datalog.datomic.test.pagination.cursor.subUnique

import molecule.coreTests.test.pagination.cursor.subUnique._
import molecule.datalog.datomic.setup.TestAsync_datomic

object AttrOrder extends AttrOrder with TestAsync_datomic
object DirectionsStandardUnique extends DirectionsStandardUnique with TestAsync_datomic
object DirectionsUniqueStandard extends DirectionsUniqueStandard with TestAsync_datomic
object MutationAdd extends MutationAdd with TestAsync_datomic
object MutationDelete extends MutationDelete with TestAsync_datomic
object Nested extends Nested with TestAsync_datomic
object NestedOpt extends NestedOpt with TestAsync_datomic
object TypesUniqueValue extends TypesUniqueValue with TestAsync_datomic
