package molecule.core.api

trait X1[A]
trait X2[A, B]
trait X3[A, B, C]
trait X4[A, B, C, D]
trait X5[A, B, C, D, E]
trait X6[A, B, C, D, E, F]
trait X7[A, B, C, D, E, F, G]
trait X8[A, B, C, D, E, F, G, H]
trait X9[A, B, C, D, E, F, G, H, I]
trait X10[A, B, C, D, E, F, G, H, I, J]
trait X11[A, B, C, D, E, F, G, H, I, J, K]
trait X12[A, B, C, D, E, F, G, H, I, J, K, L]
trait X13[A, B, C, D, E, F, G, H, I, J, K, L, M]
trait X14[A, B, C, D, E, F, G, H, I, J, K, L, M, N]
trait X15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O]
trait X16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
trait X17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q]
trait X18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
trait X19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S]
trait X20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T]
trait X21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U]
trait X22[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V]
trait X23[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X]
trait X24[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y]
trait X25[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, X, Y, Z]