package molecule.core.api

import molecule.base.error.ModelError
import molecule.core.ast.DataModel.*

// Initiate right join
trait OptEntityOp_0[Entity[_, _]] {
  protected def _optEntity[OptEntityTpl](attrs: List[Attr]): Entity[Option[OptEntityTpl], Any] = ???
}
trait OptEntity_0[Entity[_, _]] { self: OptEntityOp_0[Entity] =>
  private def getAttrs(optEntity: Molecule): List[Attr] = optEntity.elements.map {
    case a: Attr => a
    case _       => throw ModelError("Only attributes allowed in optional entity.")
  }

  final def ?                                                                   (optEntity: Molecule_00                                                                  ): Entity[Option[Any                                                               ], Any] = _optEntity[Any                                                               ](getAttrs(optEntity))
  final def ?[a                                                               ] (optEntity: Molecule_01[a                                                               ]): Entity[Option[a                                                                 ], Any] = _optEntity[a                                                                 ](getAttrs(optEntity))
  final def ?[a, b                                                            ] (optEntity: Molecule_02[a, b                                                            ]): Entity[Option[(a, b                                                            )], Any] = _optEntity[(a, b                                                            )](getAttrs(optEntity))
  final def ?[a, b, c                                                         ] (optEntity: Molecule_03[a, b, c                                                         ]): Entity[Option[(a, b, c                                                         )], Any] = _optEntity[(a, b, c                                                         )](getAttrs(optEntity))
  final def ?[a, b, c, d                                                      ] (optEntity: Molecule_04[a, b, c, d                                                      ]): Entity[Option[(a, b, c, d                                                      )], Any] = _optEntity[(a, b, c, d                                                      )](getAttrs(optEntity))
  final def ?[a, b, c, d, e                                                   ] (optEntity: Molecule_05[a, b, c, d, e                                                   ]): Entity[Option[(a, b, c, d, e                                                   )], Any] = _optEntity[(a, b, c, d, e                                                   )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f                                                ] (optEntity: Molecule_06[a, b, c, d, e, f                                                ]): Entity[Option[(a, b, c, d, e, f                                                )], Any] = _optEntity[(a, b, c, d, e, f                                                )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g                                             ] (optEntity: Molecule_07[a, b, c, d, e, f, g                                             ]): Entity[Option[(a, b, c, d, e, f, g                                             )], Any] = _optEntity[(a, b, c, d, e, f, g                                             )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h                                          ] (optEntity: Molecule_08[a, b, c, d, e, f, g, h                                          ]): Entity[Option[(a, b, c, d, e, f, g, h                                          )], Any] = _optEntity[(a, b, c, d, e, f, g, h                                          )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i                                       ] (optEntity: Molecule_09[a, b, c, d, e, f, g, h, i                                       ]): Entity[Option[(a, b, c, d, e, f, g, h, i                                       )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i                                       )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j                                    ] (optEntity: Molecule_10[a, b, c, d, e, f, g, h, i, j                                    ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j                                    )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j                                    )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k                                 ] (optEntity: Molecule_11[a, b, c, d, e, f, g, h, i, j, k                                 ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k                                 )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k                                 )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l                              ] (optEntity: Molecule_12[a, b, c, d, e, f, g, h, i, j, k, l                              ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l                              )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l                              )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m                           ] (optEntity: Molecule_13[a, b, c, d, e, f, g, h, i, j, k, l, m                           ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m                           )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m                           )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ] (optEntity: Molecule_14[a, b, c, d, e, f, g, h, i, j, k, l, m, n                        ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n                        )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n                        )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ] (optEntity: Molecule_15[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o                     )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ] (optEntity: Molecule_16[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p                  )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ] (optEntity: Molecule_17[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q               )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ] (optEntity: Molecule_18[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r            )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ] (optEntity: Molecule_19[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s         )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ] (optEntity: Molecule_20[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t      )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ] (optEntity: Molecule_21[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   ]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   )], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u   )](getAttrs(optEntity))
  final def ?[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v] (optEntity: Molecule_22[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v]): Entity[Option[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v)], Any] = _optEntity[(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v)](getAttrs(optEntity))
}

