package molecule.sql.mariadb.compliance.pagination.cursor.subUnique

import molecule.coreTests.spi.pagination.cursor.subUnique._
import molecule.sql.mariadb.setup.TestAsync_mariadb

object Test_AttrOrder extends AttrOrder with TestAsync_mariadb
object Test_DirectionsStandardUnique extends DirectionsStandardUnique with TestAsync_mariadb
object Test_DirectionsUniqueStandard extends DirectionsUniqueStandard with TestAsync_mariadb
object Test_MutationAdd extends MutationAdd with TestAsync_mariadb
object Test_MutationDelete extends MutationDelete with TestAsync_mariadb
object Test_Nested extends Nested with TestAsync_mariadb
object Test_OptNested extends OptNested with TestAsync_mariadb
object Test_TypesUniqueValue extends TypesUniqueValue with TestAsync_mariadb
