package molecule.sql.postgres.compliance.aggr.set

import molecule.coreTests.spi.aggr.set.refNum._
import molecule.sql.postgres.setup.TestAsync_postgres

object AggrSetRefNum_sum extends AggrSetRefNum_sum with TestAsync_postgres
object AggrSetRefNum_median extends AggrSetRefNum_median with TestAsync_postgres
object AggrSetRefNum_avg extends AggrSetRefNum_avg with TestAsync_postgres
object AggrSetRefNum_variance extends AggrSetRefNum_variance with TestAsync_postgres
object AggrSetRefNum_stddev extends AggrSetRefNum_stddev with TestAsync_postgres
