package molecule.sql.postgres.compliance.aggr.set

import molecule.coreTests.spi.aggr.set.any._
import molecule.sql.postgres.setup.TestAsync_postgres

object AggrSet_String extends AggrSet_String_ with TestAsync_postgres
object AggrSet_Int extends AggrSet_Int with TestAsync_postgres
object AggrSet_Long extends AggrSet_Long_ with TestAsync_postgres
object AggrSet_Float extends AggrSet_Float_ with TestAsync_postgres
object AggrSet_Double extends AggrSet_Double_ with TestAsync_postgres
object AggrSet_Boolean extends AggrSet_Boolean with TestAsync_postgres
object AggrSet_BigInt extends AggrSet_BigInt_ with TestAsync_postgres
object AggrSet_BigDecimal extends AggrSet_BigDecimal_ with TestAsync_postgres
object AggrSet_Date extends AggrSet_Date_ with TestAsync_postgres
object AggrSet_DurationDuration extends AggrSet_Duration_ with TestAsync_postgres
object AggrSet_InstantInstant extends AggrSet_Instant_ with TestAsync_postgres
object AggrSet_LocalDateLocalDate extends AggrSet_LocalDate_ with TestAsync_postgres
object AggrSet_LocalTimeLocalTime extends AggrSet_LocalTime_ with TestAsync_postgres
object AggrSet_LocalDateTimeLocalDateTime extends AggrSet_LocalDateTime_ with TestAsync_postgres
object AggrSet_OffsetTimeOffsetTime extends AggrSet_OffsetTime_ with TestAsync_postgres
object AggrSet_OffsetDateTimeOffsetDateTime extends AggrSet_OffsetDateTime_ with TestAsync_postgres
object AggrSet_ZonedDateTimeZonedDateTime extends AggrSet_ZonedDateTime_ with TestAsync_postgres
object AggrSet_UUID extends AggrSet_UUID_ with TestAsync_postgres
object AggrSet_URI extends AggrSet_URI_ with TestAsync_postgres
object AggrSet_Byte extends AggrSet_Byte_ with TestAsync_postgres
object AggrSet_Short extends AggrSet_Short_ with TestAsync_postgres
object AggrSet_Char extends AggrSet_Char_ with TestAsync_postgres
object AggrSet_ref extends AggrSet_ref with TestAsync_postgres
