package molecule.sql.sqlite.compliance.pagination.cursor.noUnique

import molecule.coreTests.spi.pagination.cursor.noUnique._
import molecule.sql.sqlite.setup.TestAsync_sqlite

object Test_AttrOrderMandatory extends AttrOrderMandatory with TestAsync_sqlite
object Test_AttrOrderOptional extends AttrOrderOptional with TestAsync_sqlite
object Test_DirectionsMandatory extends DirectionsMandatory with TestAsync_sqlite
object Test_DirectionsOptional extends DirectionsOptional with TestAsync_sqlite
object Test_MutationAdd extends MutationAdd with TestAsync_sqlite
object Test_MutationDelete extends MutationDelete with TestAsync_sqlite
object Test_Nested extends Nested with TestAsync_sqlite
object Test_OptNested extends OptNested with TestAsync_sqlite
object Test_TypesOptional extends TypesOptional with TestAsync_sqlite
