package boilerplate.db.core

object CoreGenerator extends App {
  //  action._Insert.generate()
  //  api._Molecules.generate()
  //  ast._Element.generate()
  //  api.expression._ExprAttr.generate()
  //  api.expression._ExprBArMan.generate()
  //  api.expression._ExprBArOpt.generate()
  //  api.expression._ExprBArTac.generate()
  //  api.expression._ExprOneMan.generate()
  //  api.expression._ExprOneOpt.generate()
  //  api.expression._ExprOneTac.generate()
  //  api.expression._ExprSetMan.generate()
  //  api.expression._ExprSetOpt.generate()
  //  api.expression._ExprSetTac.generate()
  //  api.expression._ExprSeqMan.generate()
  //  api.expression._ExprSeqOpt.generate()
  //  api.expression._ExprSeqTac.generate()
  //  api.expression._ExprMapMan.generate()
  //  api.expression._ExprMapOpt.generate()
  //  api.expression._ExprMapTac.generate()
  //  api._Aggregates.generate()
  //  api._ModelOps.generate()
  //  api._Nested.generate()
  //  api._OptRef.generate()
  //  api._SortAttrs.generate()
  //  marshalling.deserialize._UnpickleTpl.generate()
  //  marshalling.serialize._PickleTpl.generate()
  //  ops._ModelTransformations.generate()
  //  transaction._InsertResolvers.generate()
  //  transaction._InsertValidators.generate()
  //  validation.insert._InsertValidationResolvers.generate()
}
