package molecule.sql.postgres.compliance.aggr.one

import molecule.coreTests.spi.aggr.one.refNum._
import molecule.sql.postgres.setup.TestAsync_postgres

object AggrOneRefNum_sum extends AggrOneRefNum_sum with TestAsync_postgres
object AggrOneRefNum_median extends AggrOneRefNum_median with TestAsync_postgres
object AggrOneRefNum_avg extends AggrOneRefNum_avg with TestAsync_postgres
object AggrOneRefNum_variance extends AggrOneRefNum_variance with TestAsync_postgres
object AggrOneRefNum_stddev extends AggrOneRefNum_stddev with TestAsync_postgres
