package molecule.document.mongodb.compliance.crud

import molecule.coreTests.spi.crud.update.one.types._
import molecule.document.mongodb.setup.TestAsync_mongodb

object UpdateOne_String_ extends UpdateOne_String_ with TestAsync_mongodb
object UpdateOne_Int extends UpdateOne_Int with TestAsync_mongodb
object UpdateOne_Long_ extends UpdateOne_Long_ with TestAsync_mongodb
object UpdateOne_Float_ extends UpdateOne_Float_ with TestAsync_mongodb
object UpdateOne_Double_ extends UpdateOne_Double_ with TestAsync_mongodb
object UpdateOne_BigInt_ extends UpdateOne_BigInt_ with TestAsync_mongodb
object UpdateOne_BigDecimal_ extends UpdateOne_BigDecimal_ with TestAsync_mongodb
object UpdateOne_Date_ extends UpdateOne_Date_ with TestAsync_mongodb
object UpdateOne_Duration_ extends UpdateOne_Duration_ with TestAsync_mongodb
object UpdateOne_Instant_ extends UpdateOne_Instant_ with TestAsync_mongodb
object UpdateOne_LocalDate_ extends UpdateOne_LocalDate_ with TestAsync_mongodb
object UpdateOne_LocalTime_ extends UpdateOne_LocalTime_ with TestAsync_mongodb
object UpdateOne_LocalDateTime_ extends UpdateOne_LocalDateTime_ with TestAsync_mongodb
object UpdateOne_OffsetTime_ extends UpdateOne_OffsetTime_ with TestAsync_mongodb
object UpdateOne_OffsetDateTime_ extends UpdateOne_OffsetDateTime_ with TestAsync_mongodb
object UpdateOne_ZonedDateTime_ extends UpdateOne_ZonedDateTime_ with TestAsync_mongodb
object UpdateOne_UUID_ extends UpdateOne_UUID_ with TestAsync_mongodb
object UpdateOne_URI_ extends UpdateOne_URI_ with TestAsync_mongodb
object UpdateOne_Byte_ extends UpdateOne_Byte_ with TestAsync_mongodb
object UpdateOne_Short_ extends UpdateOne_Short_ with TestAsync_mongodb
object UpdateOne_Char_ extends UpdateOne_Char_ with TestAsync_mongodb
