package molecule.sql.mariadb.compliance.aggr.set

import molecule.coreTests.spi.aggr.set.refNum._
import molecule.sql.mariadb.setup.TestAsync_mariadb

object AggrSetRefNum_sum extends AggrSetRefNum_sum with TestAsync_mariadb
object AggrSetRefNum_median extends AggrSetRefNum_median with TestAsync_mariadb
object AggrSetRefNum_avg extends AggrSetRefNum_avg with TestAsync_mariadb
object AggrSetRefNum_variance extends AggrSetRefNum_variance with TestAsync_mariadb
object AggrSetRefNum_stddev extends AggrSetRefNum_stddev with TestAsync_mariadb
