package molecule.datalog.datomic.compliance.validation.insert

import molecule.coreTests.spi.validation.insert._
import molecule.datalog.datomic.setup.Test_datomic_async

object Test_FormatConstants  extends FormatConstants with Test_datomic_async
object Test_FormatVariables extends FormatVariables with Test_datomic_async
object Test_Nested extends Nested with Test_datomic_async
object Test_Semantics extends Semantics with Test_datomic_async
object Test_TypesOne extends TypesOne with Test_datomic_async
object Test_TypesOneOpt extends TypesOneOpt with Test_datomic_async
object Test_TypesSeq extends TypesSeq with Test_datomic_async
object Test_TypesSeqOpt extends TypesSeqOpt with Test_datomic_async
object Test_TypesSet extends TypesSet with Test_datomic_async
object Test_TypesSetOpt extends TypesSetOpt with Test_datomic_async
